### PR TITLE
✨ TWEAK: add code of conduct

### PR DESCRIPTION
**Pull request by warengonzaga**
Hey, I added a code of conduct to the project, and also update the issue form to add a checkmark for following our code of conduct. Check the new look of the issue form. Let me know if want to add more here.

image

Also, I want to know what email to use for the code of conduct? Who to contact about the project?
I temporarily use `opensource@email.com` which is a dummy...

### CODE REVIEW

**Comment by warengonzaga** [comment]
Let me know what email to use @tandpfun, thanks! ;)

**Comment by tandpfun** [comment]
Hmm, I don't think this is completely necessary for issues right now. I might make contribution guidelines at some point for pull requests and how to contribute, but I don't see a purpose for a code of conduct at this time.

**Comment by warengonzaga** [comment]
Alright, @tandpfun I'm gonna keep this for now?

**Comment by tandpfun** [comment]
I'm going to close it for now, but I'll reopen if there's a need in the future. I appreciate the contributions!

**Pull request closed without merging**
