### PR TITLE
Icons: Ableton, Adobe Audition, rollup.js

### PR DESCRIPTION
**Pull request by tetra-fox**
<table>
<tr>
        <th>Icon
	<th>Dark
	<th>Light
<tr align="center">
	<td>Ableton
	<td>
	<td>
<tr align="center">
	<td>Audition
	<td colspan="2">
<tr align="center">
	<td>RollupJS
	<td>
	<td>
</table>

### CODE REVIEW

**Review by skepfusky — CHANGES_REQUESTED** [review]
It's all good, though you might need to add some spacing on the Audition logo on the readme to center it

**Comment by tetra-fox** [comment]
Should be good now.
I'd also like to suggest that maybe the icon table be switched to one created with HTML tags, rather than markdown, as I've done in my original PR comment. This would allow the ability to add `align="center"` attributes to table elements and remove the need for manual spacing.
It's out of this PR's scope, though maybe another issue could be opened.

**Comment by skepfusky** [comment]
I know it's pretty unrelated to this PR - I might consider it, but it's all good now!

**Review by skepfusky — APPROVED** [review]

**Comment by tandpfun** [comment]
I don't normally accept PRs for icons, as svgs a pretty finicky with browser support on certain editors. I'll try to implement these, but I'll have to re-export them with figma.

**Pull request merged**
