### PR TITLE
Update Appwrite.svg

### PR DESCRIPTION
**Pull request by Honzoraptor31415**
Because the icon had a weird white background and it wasn't even the icon Appwrite currentely uses on their website.

### CODE REVIEW

**Comment by Honzoraptor31415** [comment]
The size of the new icon is a little off tho.

**Comment by LelouchFR** [comment]
> The size of the new icon is a little off tho.

The size matter, did you ran your code ?

**Comment by Honzoraptor31415** [comment]
> > The size of the new icon is a little off tho.
> 
> The size matter, did you ran your code ?

No sorry, this is just a suggestion, I think the icon should be remade by a professional.

**Comment by artifishvr** [comment]
> I think the icon should be remade by a professional.

#736 is made by a member of the appwrite team, same contributor as the currently used one (#35) c:

**Pull request closed without merging**
