### PR TITLE
Added Regex icon

### PR DESCRIPTION
**Pull request by ArjixWasTaken**

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Looks like this
image

**Comment by ArjixWasTaken** [comment]
I used the color pallet of the vscode dracula theme

**Comment by ArjixWasTaken** [comment]
Any edits are welcome!

**Comment by tandpfun** [comment]
Thank you for your contribution! However, the theme of the icon doesn't exactly match the current formatting of the icons, or support the way that the themes work. I prefer that issues are opened to suggest an icon's addition to the project!

Be sure to test your icons with miniflare by running `yarn dev` to make sure everything works before creating a pull request.

I can design the icon to match the theme with the svg you provided if you'd like!

**Comment by ArjixWasTaken** [comment]
> I can design the icon to match the theme with the svg you provided if you'd like!

Great!

**Comment by ThatOneCalculator** [comment]
Potentially superseded by #5

**Pull request closed without merging**
