### PR TITLE
ICONS: Linux, Haxe, Godot, Scala, Regex, SVG, Remix, Solidity

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Linux-Light Linux-Dark 

Haxe-Light Haxe-Dark

Godot-Light Godot-Dark 

Scala-Light Scala-Dark

Regex-Light Regex-Dark

SVG-Light SVG-Dark

Remix

Solidity

Linux icon source is from Flat Color Icons and under the MIT license. All other icons are the original logo SVGs.

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
@tandpfun I ended up adding a couple more than initially planned ^^"

**Comment by ThatOneCalculator** [comment]
Also added ReGeX, which fixes #1

**Comment by tandpfun** [comment]
Thank you! I'll take a look in a bit. I appreciate these contributions but it can get kind of confusing with the svgs, branches, readmes, and just so much to make sure is in order. I'll likely go through and merge these, but I might make adding icons be through issues only in the future so I can make sure everything is in order.

**Comment by ThatOneCalculator** [comment]
Awesome! I did run and test everything locally to make sure it worked, and as this is on a singular branch, there's no need to worry about branches.

**Comment by tandpfun** [comment]
For remix, could you make a light theme icon as well?

**Comment by ThatOneCalculator** [comment]
> For remix, could you make a light theme icon as well?

Remix doesn't like having their brand colors changed, that's why the background is a diff color. If you want, I can, but I wouldn't recommend it.

**Comment by tandpfun** [comment]
The godot logo is a PNG inside an SVG

**Comment by ThatOneCalculator** [comment]
> The godot logo is a PNG inside an SVG

Ack, thought I imported the SVG! Give me a minute, I'll fix it.

**Comment by ThatOneCalculator** [comment]
@tandpfun fixed!

**Comment by ThatOneCalculator** [comment]
Added the proposed Discord bots icon from #6
DiscordBots

**Comment by ThatOneCalculator** [comment]
Reverted Discord Bot proposal icon @tandpfun

**Comment by ThatOneCalculator** [comment]
All done.

**Comment by ThatOneCalculator** [comment]
> What program did you design these in? I might want original files (or like a link to the project if figma) so I can have em all in my program for future releases and stuff.

Inkscape. The uploaded files are the originals.

**Comment by ThatOneCalculator** [comment]
> for future releases and stuff.

Wait, so would the currently proposed icons be merged or would you want to edit them and release it in the future?

**Comment by ArjixWasTaken** [comment]
Regex doesn't have an official logo...
But I can agree that this is better than the one in my PR, would be nice if you instead helped improve my own PR, but oh well.

**Comment by tandpfun** [comment]
> > for future releases and stuff.
> 
> 
> 
> Wait, so would the currently proposed icons be merged or would you want to edit them and release it in the future?
> 
> 

Yeah so that's my issue with PRs of icons - I'd prefer to have the icons in figma so I can edit or export em, and make sure they're in the same format. I feel bad turning down prs and work people do, so I thought I'd try to merge yours. It's just a lot of work to handle icon PRs like this.

**Comment by tandpfun** [comment]
image
doesn't look like the icons are cross compatible

**Comment by tandpfun** [comment]
I might remake them in figma to export them in the right formats. I'm not sure why this happened, probably to do with issues combining em into one svg.

**Comment by tandpfun** [comment]
Thank you all for your work on this!! The svg icon had some weird issues and I don't have time to figure it out, so I'll probably add it later on. Sorry for how long it took!

From now on I'd appreciate if icons are suggested in issues with reference images (or upload the icons you create as an svg into the issue) so that stuff is more uniform. But that doesn't mean I don't appreciate this, thank you for all your work!!

**Pull request merged**
